캐쉬 
select * from SPMKT.TST_OD_CASH_OCCR_HST;       -- 캐시 발생 이력
select * from SPMKT.TST_OD_CASH_OCCR_DTL_HST;   -- 캐시 발생 상세 이력
select * from SPMKT.TST_OD_CASH_CMPR_HST;       -- 캐시 대사 이력
select * from SPMKT.TST_OD_CASH_OCCR_STATS_HST; -- 캐시 발생 통계 이력

이벤트 
select * from tbl_event;

스패셜이벤트
select * from TBL_SSNL_EVENT;               -- 이벤트 메인
select * from TBL_SSNL_EVENT_EXCP_HP;       -- 제외 단말
select * from TBL_SSNL_EVENT_FILE;          -- 파일
select * from TBL_SSNL_EVENT_TARG_DEVICE;   -- 대상 단말

-- 사전예약
TST_DC_EVENT_BASE;                -- EVENT_CASE_CD - MK002201:구매혜택, MK002205:사전예약
TST_DC_EVENT_BEFH_PRENG;          -- 사전_예약_이벤트
TST_DC_EVENT_BEFH_PRENG_ALL;      -- 사전_예약_이벤트_모든_예약
TST_DC_EVENT_BEFH_PRENG_INST;     -- 사전_예약_이벤트_자동_설치
TST_DC_EVENT_BEFH_PRENG_NOTFCT;   -- 사전_예약_이벤트_오픈_알림
TST_DC_EVENT_BEFH_PRENG_PCOND;    -- 사전_예약_이벤트_신청_현황
TST_DC_EVENT_BEFH_PRENG_SEPR;     -- 사전_예약_이벤트_개별_예약

TST_DC_DVLPR_BEFH_PRENG_PCOND

TST_DC_EVENT_BASE
TST_DC_EVENT_BEFH_PRENG
TST_DC_EVENT_AUTO_PYMT;   -- 자동_결제_이벤트
TST_DC_EVENT_TARGET_PROD_CASE;    -- 이벤트_대상_상품_유형
TST_DC_EVENT_GIFTCD;    -- 기프트_카드_이벤트
TST_DC_EVENT_TARGET_DEF;    -- 이벤트_대상_정의
TST_DC_EVENT_TARGET_CATEGORY
TB_DP_MENU_CATEGORY_PROD_MAPG
TB_DP_PROD DP
TB_DP_TENANT_PROD
TB_DP_PROD_DESC


TST_DC_EVENT_BEFH_PRENG
TST_DC_EVENT_AUTO_PYMT
TST_DC_EVENT_BASE
TST_DC_EVENT_TARGET_PROD_CASE
TST_DC_EVENT_GIFTCD
TST_DC_EVENT_TARGET_DEF


TST_DC_CPN_EXCL;    -- 쿠폰_제외
TST_DC_CPN_TENANT;  -- 쿠폰_테넌트
TST_DC_CPN_BASE;    -- 쿠폰_기본
TST_DC_CPN_DTL;     -- 쿠폰_상세
TST_DC_CPN_LIMT_CNT;    -- 쿠폰_제한_수량
TST_DC_EVENT_PRIOR_DEF; -- 이벤트_우선_순위_정의

TB_DP_MENU_CATEGORY
TB_DP_MENU_CATEGORY_DESC
TB_DP_APP_PROD
TB_DP_TENANT_PROD
TB_DP_PROD_DESC
TB_DP_PROD
TB_DP_PROD_CATALOG_MAPG
TB_DP_PROD_RSHP
TB_US_SELLERMBR
TST_DC_CPN_EXCL
TST_DC_CPN_TENANT
TB_US_OUSERMBR
TB_US_OUSERMBR_DEVICE


TST_DC_EVENT_BASE
TST_DC_EVENT_TARGET_PROD_CASE
TST_DC_EVENT_GIFTCD
TST_DC_EVENT_DESC
TST_DC_EVENT_FILE
TST_DC_EVENT_TARGET_UPLOD
TST_DC_EVENT_TARGET_UPLOD_RVIS
TB_US_OUSERMBR
TST_DC_EVENT_LIMT
TST_DC_EVENT_AUTO_PAY
TST_DC_EVENT_BASE


TB_US_OUSERMBR
TB_US_OUSERMBR_DEVICE
TST_OD_CASH_OCCR_HST
TST_GIFT_CARD_DRBK_OCCR_HST
TST_GIFT_CARD_CHRG_RWD_HST

TBL_AD_MGR - FN_MASK_NAME, FN_MASK_ID

TB_US_OUSERMBR;
TB_US_OUSERMBR_DEVICE;
TST_OD_CASH_OCCR_HST;
TST_GIFT_CARD_DRBK_OCCR_HST; -- 기프트_카드_환불_발생_이력
TST_GIFT_CARD_CHRG_RWD_HST;   -- 기프트_카드_충전_리워드_이력


TB_US_OUSERMBR
TB_US_OUSERMBR_DEVICE
TBL_COMM_CD
TST_OD_CASH_OCCR_HST
TST_OD_CASH_OCCR_DTL_HST

TB_PR_PRCHS_DTL     
TB_DP_PROD_DESC
TOP_MENU_ID
TST_DC_CASH_ORDER_PROD
TST_PT_GIFT_CARD_DTL
TST_PT_GIFT_CARD
TST_DC_CASH_ORDER_PROD


TST_DC_PUSH_NOTFCT
TST_DC_EVENT_BEFH_PRENG_PCOND

TST_DC_CPN_TENANT
TST_DC_CPN_BASE
TST_DC_CPN_DTL
TST_DC_CPN_RN
TST_DC_CPN_RN_HIS
TST_DC_CPN_LIMT_CNT

TST_DC_CPN_BASE
TST_DC_CPN_DTL
TST_DC_CPN_LIMT_CNT
TST_DC_CPN_TENANT
TST_DC_CPN_DTL_HIS

TST_DC_CPN_TENANT
TST_DC_CPN_BASE
TST_DC_CPN_DTL
TST_DC_CPN_LIMT_CNT

TST_DC_EVENT_BASE
TST_DC_EVENT_BEFH_PRENG
TST_DC_EVENT_AUTO_PYMT
TST_DC_EVENT_TARGET_PROD_CASE
TST_DC_EVENT_GIFTCD
